#!/bin/bash
#SBATCH --mail-type=all
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --job-name="TU_HaplotypeCaller"
#SBATCH --time=60:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=40G

module load vital-it/7

module load UHTS/Analysis/GenomeAnalysisTK/4.2.0.0

SAMPLES_FILE=/storage/workspaces/vetsuisse_fiwi_epev/fiwi_epev001/datasets/dataset_collection/zebrafish/novogene_080622/sample_codes_TU.txt
# reference genome
GENOME=/storage/homefs/zw21s077/zhihui/reference/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa

#/storage/homefs/zw21s077/zhihui/TU/RG_added

for i in `cat $SAMPLES_FILE`;do
gatk --java-options "-Xmx4g" HaplotypeCaller  \
   -R ${GENOME} \
   -I /storage/homefs/zw21s077/zhihui/TU/RG_added/${i}_RG.bam \
   -O ${i}.vcf.gz \
   -ERC GVCF
done
