#!/bin/bash
#SBATCH --mail-type=all
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --job-name="RG-add"
#SBATCH --time=01:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=100G


module load vital-it/7

module load UHTS/Analysis/picard-tools/2.21.8
module load UHTS/Analysis/samtools/1.10

mkdir RG_added

for file in `ls *aligned_MAPQ20_rdup.bam`; do

export iden=${file%%_*}
export output=${iden}_RG.bam
export ID=HH5TGBX2.${iden}
export LB=Lib.${iden}.1_4
export PU=HH5TGBX2.1_4.${iden}

picard-tools AddOrReplaceReadGroups I=${file} O=${output} RGID=${ID} RGLB=${LB} RGPL=ILLUMINA RGPU=${PU} RGSM=${iden}

samtools index ${output}

mv ${output} RG_added
mv ${output}.bai RG_added

done
